var _ = require('lodash');

var fakeArticle = {
    title: 'Water Pricing in Two Thirsty Cities: In One, Guzzlers Pay More, and Use Less',
    top_image: 'http://static01.nyt.com/images/2015/05/06/business/20150507WATERMARKETS-SS-slide-XI20/20150507WATERMARKETS-SS-slide-XI20-jumbo.jpg',
    text: 'FRESNO, Calif. — When residents of this parched California city opened their water bills for April, they got what Mayor Ashley Swearengin called “a shock to the system. ”The city had imposed a long-delayed, modest rate increase — less than the cost of one medium latte from Starbucks for the typical household, and still leaving the price of water in Fresno among the lowest across the entire Western United States. But it was more than enough to risk what the mayor bluntly admits could be political suicide .“It wasn’t that long ago,” Ms. Swearengin said, “that people here were fighting the installation of water meters. ”Nearly 15 years ago and 1,000 miles away in Santa Fe, N.M., officials faced a similarly dire predicament when a drought came within a few thousand gallons of leaving the city without enough water to fight fires. But Santa Fe’s response was far more audacious .Santa Fe, in addition to raising the basic cost of water, decided to make the heaviest users of water pay more — much more — for the water they consumed .Known as tiered pricing, the system wasn’t new or unique to Santa Fe, but in no major city today are the tiers so steep, with water guzzlers paying three to four times more per gallon than more efficient consumers are charged .“It was a big wake-up call,” said Rick Carpenter, manager of water resources and conservation for Santa Fe. “There was some opposition, and it could easily have gone the other way. But the majority saw we needed to band together on this one. ”In moving away from the idea that water should be cheap for everybody just because it is so essential to life, Santa Fe’s approach to water pricing offers lessons in how other parched cities can balance the societal costs of scarcer, more expensive water in a relatively equitable way .Because of the huge gap between tiers, the biggest consumers effectively subsidize everyone else, shielding poorer residents from feeling the full brunt of rate increases .“So much turns on pricing when it comes to water,” said Robert Glennon, a professor at the Rogers College of Law at the University of Arizona and the author of “Unquenchable: America’s Water Crisis and What to Do About It,” a 2009 book on water policy.'
}


module.exports = _.map(_.range(30), function() {
    return fakeArticle
});
